### ISSUE TITLE
SELinux makes authorized_keys unreadable

### ISSUE THREAD

**Issue by Mikulas** [silpion/ansible-gitolite#4]
I assume this is due to default location being under `/srv`

Required fix:
```
chcon -Rv -t ssh_home_t ~git/.ssh
```

Without this all ssh connections as `git` user fail.

**Comment by spul** [comment]
Hi, this is already fixed in our blessed repos. Gonna push a number of updates/roles today.

**Comment by Mikulas** [comment]
Awesome, thanks :)

**Comment by spul** [comment]
Addressed with [2.0.0][1].

[1]: https://github.com/silpion/ansible-gitolite/tree/2.0.0
