### ISSUE TITLE
Ansbile 2.1: issue with become in admin.yml

### ISSUE THREAD

**Issue by jardleex** [silpion/ansible-gitolite#5]
Hi,

I just encountered a error running this role with Ansible 2.1.0.0:

`TASK [silpion.gitolite : Install gitolite.conf] ********************************
Friday 24 June 2016  10:24:42 +0200 (0:00:01.544)       0:00:29.463 *********** 
fatal: [MYHOSTNAME]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user. For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}`

As described in the link I then commented out the both become lines on the task _Install gitolite.conf_. Afterwards the playbook worked again.

May you take a look at this? The role seem to need a review to work with the recent Ansible version.

Best regards

Jard

PS: I also saw some deprecations warnings on bare variable usages.

**Comment by spul** [comment]
Hi,

currently there is really not much time for managing things like that, but I'll have that issued in our internal tracker and try to provide a fix as soon as possible.

**Comment by jardleex** [comment]
Hi,

thank you for your reply, I'll keep an eye on this issues here.
I bypassed my issue with commenting out the become lines at the mentioned tasks.

**Comment by spul** [comment]
Hi, in blessed repository I've that one fixed. Waiting for PR approval prior to publish a new release.

**Comment by spul** [comment]
Release 2.1.0 address the issue. Thanks again :)

**Comment by jardleex** [comment]
Hi,

thank you for taking care but unforutnetly I still get the error.

`TASK [silpion.gitolite : Install gitolite.conf] ********************************
Sunday 31 July 2016  15:14:14 +0200 (0:00:01.435)       0:00:14.776 *********** 
fatal: [control1.lan.herob.local]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user. For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}
`

If I then comment the both become lines on the task mentioned the error is gone.
I just setup a new VM without any configurations for the role and the error still comes up.

Can you confirm this?

**Comment by spul** [comment]
Hi, I was on holidays; sorry for the delay. Just fetched the repository anew, `rake provision` with

* vagrant 1.8.4 libvirt
* vagrant 1.8.5 virtualbox

both function properly.

**Comment by jardleex** [comment]
Hi, I was also on holidy, so no problem here.

I'll try to test it with rake in my environment as well.
Feedback follows.

**Comment by jardleex** [comment]
[SOLVED]

I can're reproduce the issue any longer. In the meantime I changed the location of my external roles, maybe something was messed up with the old one I used.
