### ISSUE TITLE
Old gitolite breaks setup on new-ish systems

### ISSUE THREAD

**Issue by dnmvisser** [silpion/ansible-gitolite#6]
`vars/main.yml` mentions:
```
gitolite_tag: 'v3.6.1'
```
Which,  according to https://github.com/sitaramc/gitolite/releases, is more than two years old.

This version uses a regular expression to check the SSH public key fingerprint generated by the OpenSSH `ssh-keygen` utility.  The regex is not compatible with the fingerprints that are generated by OpenSSH 6.8 and newer. As a result the setup will fail with an error like this:

> FATAL: fingerprinting failed for 'keydir/id_rsa.pub'"

This problem is fixed in Gitolite 3.6.3.
Since this is not overridable using `defaults` - can the version in `vars/main.yml` please be bumped to (at least) `v3.6.3`?

Ubuntu 14.04 has OpenSSH 6.6, so there things are OK.
But when moving to Ubuntu 16.04, OpenSSH is 7.2, so then this issue surfaced.

**Comment by spul** [comment]
Hi, this role definitely needs some love. I'll try to look at the PR asap + further "required" updates.

**Comment by spul** [comment]
This is addressed with release 2.1.0. `gitolite_tag` variable from vars has been removed in favor of `gitolite_version` in defaults.
