### ISSUE TITLE
Include facts management - broken

### ISSUE THREAD

**Issue by jardleex** [silpion/ansible-gitolite#8]
Hi,

I just checked out version 2.1.0 and stumbled over the new task **Include facts management** in the tasks/main.yml.

```
TASK [silpion.gitolite : Include facts management] *****************************
Sunday 31 July 2016  15:24:01 +0200 (0:00:01.509)       0:00:41.870 *********** 
fatal: [gittest.lan.herob.local]: FAILED! => {"failed": true, "reason": "the file_name '/home/foo/Dokumente/git/ansible/roles/silpion.lib/tasks/localfacts.yml' does not exist, or is not readable"}
```

As all my external roles live under a folder called galaxy the default assumtion made here breaks the whole role for me.

Situation on my machine

```
roles/ # contains only roles written by me
galaxy/ # contains roles from Ansible-Galaxy and other external sources
```

Situation assumed:

```
roles/ # all roles used living here
```

It would be nice to be able to override this default within a variable in my host_vars/gitserver file.
Maybe something like this:

```
# defaults/main.yml
gitolite_lib_path: '{{ playbook_dir }}/roles/silpion.lib'

# tasks/main.yml
- name: Include facts management
  tags: gitolite
  include: '{{ gitolite_lib_path }}/tasks/localfacts.yml'
  vars:
    namespace: gitolite
```

**Comment by spul** [comment]
This will get fixed with Ansible `2.2`, when `include` allows to reference a role where to include from. For now we need to do that this way. When 2.2 arrives, AND ansible supports role- aware includes, we'll update all roles using silpion.lib or silpion.util.

Anyway your suggestion totally makes sense and I'll talk with the guys writing on roles here if we're going to address this in general.

For a short term solution I'd suggest to `ln -s galaxy/silpion.lib roles/silpion.lib`.

**Comment by jardleex** [comment]
Thanks for the advise for Ansible 2.2. Looking forward to it.

I'll remove my bypass and try the temporary symlink instead.
Will give feedback asap.

**Comment by jardleex** [comment]
Creating the symlink bypassed my issue:

`ln -s ../galaxy/silpion.lib roles/silpion.lib`

I'll keep an eye on the new Ansible release and will try it then without the link.

Thank you for your help!

**Comment by spul** [comment]
Hi, current release 2.1.1 introduces another variable which allows for configuration of a path where to look for silpion.lib role.

**Comment by jardleex** [comment]
Hi,
just updated and used the new config option.

Thank's for sharing this detail!
